export interface Person {
  id: number;
  imgSrc: string;
  imgAlt?: string;
  imgPosition?: string;
  funkyStyles?: boolean;
  firstName: string;
  lastName: string;
  role: { en: string; de: string };
  description: { en: string; de: string };
  phone?: string;
  email?: string;
  homepage?: string;
  homepageText?: string;
  facebook?: string;
  instagram?: string;
  youtube?: string;
  soundcloud?: string;
  github?: string;
  bandcamp?: string;
  socialOrder?: string;
}
export interface Event {
  id: number;
  imgSrc: string;
  imgPosition?: string;
  imgContainerWidth?: string;
  title: string;
  date: Date;
  dateText?: string;
  link?: string;
  linkText?: string;
  location: string;
  description?: string;
  phone?: string;
  email?: string;
  emailText?: string;
  expanded?: boolean;
  allowShare?: boolean;
  canceled?: boolean;
}
export interface Shoutout {
  id: number;
  imgSrc: string;
  imgAlt?: string;
  imgClass?: string;
  imgPosition?: string;
  // imgFit?: 'contain' | 'cover' | 'none' | 'fill' | 'scale-down' | undefined;
  imgFit?: any;
  imgWrapBgColor?: string;
  funkyStyles?: boolean;
  bgColor: string;
  title: { en: string; de: string };
  subtitle?: { en: string; de: string };
  expanded?: boolean;
  introVideo?: { en: string; de: string };
  description?: { en: string; de: string };
  readmore?: { en: string; de: string };
  phone?: string;
  email?: string;
  homepage?: { en: string; de: string };
  homepageText?: string;
  homepageIconOnly?: boolean;
  facebook?: string;
  instagram?: { en: string; de: string };
  youtube?: string;
  soundcloud?: string;
  github?: string;
  twitter?: string;
  reddit?: string;
  tiktok?: string;
  pinterest?: string;
  linkedin?: string;
  xing?: string;
  twitch?: string;
  podcast?: string;
  discord?: string;
  patreon?: string;
  bandcamp?: string;
  spotify?: string;
  shop?: { en: string; de: string };
  shopify?: { en: string; de: string };
  socialOrder?: string;
}
